routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Rutas del sitio web
//Home
Route::get('/', 'HomeMainController@ShowHome');

//About
Route::get('/nosotros', 'HomeMainController@ShowAbout');

Route::get('/nosotros/historia', function () {
    return view('others_templates.history');
});

//About-Team
Route::get('/nosotros/equipo/{slug}','HomeMainController@ShowTestimonial');

//Productos
Route::get('/productos','HomeMainController@ShowProducts');

//Productos-Producto
Route::get('/productos/{slug}','HomeMainController@ShowProduct');

//Blog
Route::get('/blog', 'HomeMainController@ShowBlogs');

//Blog-Post
Route::get('/blog/{slug}', 'HomeMainController@ShowBlog');

//Blog-Noticia
Route::get('/blog/noticia1', function () {
    return view('others_templates.blog-news');
});

//Contactanos
Route::get('/contactanos', 'ContactUSController@contactUs');
Route::post('/contactanos/store','ContactUSController@contactUSPost');

Route::get('/galeria','HomeMainController@ShowGallery');


Route::group(['middleware' => ['auth']], function() {
//Admin-Panel
//Dashboard
Route::get('/fwdfundacion/admin-panel', function () {
    return view('manager.dashboard.dashboard');
});

//Users
/* User routes */
Route::get('/fwdfundacion/admin-panel/users', 'UserController@ShowUsers');
Route::get('/fwdfundacion/admin-panel/users/create', 'UserController@CreateUser');
Route::post('/fwdfundacion/admin-panel/users/store', 'UserController@StoreUser');
Route::get('/fwdfundacion/admin-panel/users/edit/{id}', 'UserController@EditUser');
Route::post('/fwdfundacion/admin-panel/users/update/{id}', 'UserController@UpdateUser');
Route::get('/fwdfundacion/admin-panel/users/destroy/{id}', 'UserController@DestroyUser');

//About-Team
Route::get('/fwdfundacion/admin-panel/about/team', 'TeamController@ShowTeam');
Route::get('/fwdfundacion/admin-panel/about/team/create', 'TeamController@CreateTeam');
Route::post('/fwdfundacion/admin-panel/about/team/store', 'TeamController@StoreTeam');
Route::get('/fwdfundacion/admin-panel/about/team/edit/{id}', 'TeamController@EditTeam');
Route::post('/fwdfundacion/admin-panel/about/team/update/{id}', 'TeamController@UpdateTeam');
Route::get('/fwdfundacion/admin-panel/about/team/destroy/{id}', 'TeamController@DestroyTeam');

//Products
Route::get('/fwdfundacion/admin-panel/products', 'ProductController@ShowProducts');
Route::get('/fwdfundacion/admin-panel/products/create', 'ProductController@CreateProduct');
Route::post('/fwdfundacion/admin-panel/products/store', 'ProductController@StoreProduct');
Route::get('/fwdfundacion/admin-panel/products/edit/{id}', 'ProductController@EditProduct');
Route::post('/fwdfundacion/admin-panel/products/update/{id}', 'ProductController@UpdateProduct');
Route::get('/fwdfundacion/admin-panel/products/destroy/{id}', 'ProductController@DestroyProduct');

//Blog
Route::get('/fwdfundacion/admin-panel/blog', 'BlogController@ShowBlogs');
Route::get('/fwdfundacion/admin-panel/blog/create', 'BlogController@CreateBlog');
Route::post('/fwdfundacion/admin-panel/blog/store', 'BlogController@StoreBlog');
Route::get('/fwdfundacion/admin-panel/blog/edit/{id}', 'BlogController@EditBlog');
Route::post('/fwdfundacion/admin-panel/blog/update/{id}', 'BlogController@UpdateBlog');
Route::get('/fwdfundacion/admin-panel/blog/destroy/{id}', 'BlogController@DestroyBlog');

//Galeria-Imagenes
Route::get('/fwdfundacion/admin-panel/galeria/imagenes', 'ImageController@ShowImages');
Route::get('/fwdfundacion/admin-panel/galeria/imagenes/create', 'ImageController@CreateImage');
Route::post('/fwdfundacion/admin-panel/galeria/imagenes/store', 'ImageController@StoreImage');
Route::get('/fwdfundacion/admin-panel/galeria/imagenes/edit/{id}', 'ImageController@EditImage');
Route::post('/fwdfundacion/admin-panel/galeria/imagenes/update/{id}', 'ImageController@UpdateImage');
Route::get('/fwdfundacion/admin-panel/galeria/imagenes/destroy/{id}', 'ImageController@DestroyImage');

//Galeria-Videos
Route::get('/fwdfundacion/admin-panel/galeria/videos', 'VideoController@ShowVideos');
Route::get('/fwdfundacion/admin-panel/galeria/videos/create', 'VideoController@CreateVideo');
Route::post('/fwdfundacion/admin-panel/galeria/videos/store', 'VideoController@StoreVideo');
Route::get('/fwdfundacion/admin-panel/galeria/videos/edit/{id}', 'VideoController@EditVideo');
Route::post('/fwdfundacion/admin-panel/galeria/videos/update/{id}', 'VideoController@UpdateVideo');
Route::get('/fwdfundacion/admin-panel/galeria/videos/destroy/{id}', 'VideoController@DestroyVideo');

//Home-Slider
Route::get('/fwdfundacion/admin-panel/slider', 'SliderController@ShowSliders');
Route::get('/fwdfundacion/admin-panel/sliders/create', 'SliderController@CreateSlider');
Route::post('/fwdfundacion/admin-panel/sliders/store', 'SliderController@StoreSlider');
Route::get('/fwdfundacion/admin-panel/sliders/edit/{id}', 'SliderController@EditSlider');
Route::post('/fwdfundacion/admin-panel/sliders/update/{id}', 'SliderController@UpdateSlider');
Route::get('/fwdfundacion/admin-panel/sliders/destroy/{id}', 'SliderController@DestroySlider');

//Home-Testimonials
Route::get('/fwdfundacion/admin-panel/clientes-testimonios', 'TestimonialController@ShowTestimonials');
Route::get('/fwdfundacion/admin-panel/clientes-testimonios/create', 'TestimonialController@CreateTestimonial');
Route::post('/fwdfundacion/admin-panel/clientes-testimonios/store', 'TestimonialController@StoreTestimonial');
Route::get('/fwdfundacion/admin-panel/clientes-testimonios/edit/{id}', 'TestimonialController@EditTestimonial');
Route::post('/fwdfundacion/admin-panel/clientes-testimonios/update/{id}', 'TestimonialController@UpdateTestimonial');
Route::get('/fwdfundacion/admin-panel/clientes-testimonios/destroy/{id}', 'TestimonialController@DestroyTestimonial');

//Home-Patrocinadores
Route::get('/fwdfundacion/admin-panel/patrocinadores', 'PartnerController@ShowPartners');
Route::get('/fwdfundacion/admin-panel/patrocinadores/create', 'PartnerController@CreatePartner');
Route::post('/fwdfundacion/admin-panel/patrocinadores/store', 'PartnerController@StorePartner');
Route::get('/fwdfundacion/admin-panel/patrocinadores/edit/{id}', 'PartnerController@EditPartner');
Route::post('/fwdfundacion/admin-panel/patrocinadores/update/{id}', 'PartnerController@UpdatePartner');
Route::get('/fwdfundacion/admin-panel/patrocinadores/destroy/{id}', 'PartnerController@DestroyPartner');


});
// Route::get('/admin/login', 'Auth\LoginController@showLoginForm')->name('login');
// Route::post('/admin/login', 'Auth\LoginController@login');
// Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/fwdfundacion/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/fwdfundacion/login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

//Auth::routes();

//Route::get('/admin-panel', 'HomeController@index')->name('admin-panel');

app/Models/Blog.php
<?php

namespace fpmoises\Models;

use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;
use Illuminate\Database\Eloquent\Model;
use Jenssegers\Date\Date;

class Blog extends Model
{
    use HasSlug;
    protected $table = 'blogs';

    public function getSlugOptions() : SlugOptions
    {
    	return SlugOptions::create()
    	->generateSlugsFrom('title')
    	->saveSlugsTo('slug');
    }

    public function scopeName($query,$name){
      if (trim($name) == "") {

      }else
      $query->where('title',"LIKE","%$name%");
    }

    public function getCreatedAtAttribute($date){
      return new Date($date);
    }

}

resources/views/about.blade.php
@extends('layouts.global_main')
@section('title', '¿Quiénes somos? - Productos Moisés')
@section('urlcanonical','https://productosmoises.com/nosotros')
@section('description', 'Productos Moisés es un departamento agroalimentario de Misión Hacia Arriba. Nos dedicamos a la producción, comercialización y distribución de pollos, hortalizas, tilapia, café y miel.')
@section('keywords', 'productos orgánicos, productos frescos')
{{-- For FB Meta tags --}}
@section('ogtitle', 'Productos 100% orgánicos y frescos | Productos Moisés')
@section('ogurl', 'https://productosmoises.com/nosotros')
@section('ogimage', 'https://productosmoises.com/img/productos-moises-about.jpg')
@section('ogdescription', 'Nos dedicamos a la producción, comercialización y distribución de pollos, hortalizas, tilapia, café y miel.')
{{-- End For FB Meta tags --}}
@section('content')
  <section id="parallax-phrase">
      <div class="parallax-container title-center-parallax">
        <h1 class="center-align title-parallax-view">Productos Moisés</h1>
        <div class="parallax"><img src="./img/productos-moises-about.webp" alt="acerca-de-productos-moisés"></div>
      </div>
  </section>
  <section id="about" class="bg-white">
        <div class="content-wrapper">
          <div class="container">
            <div class="row">
              <div class="col s12 l6 m12">
                <h5 class="center-align no-margin sub-title">Conoce más</h5>
                <h3 class="center-align title no-margin">Sobre nosotros</h3>
                <div class="row">
                  <div class="col s12">
                    <ul class="tabs">
                      <li class="tab col s4"><a class="active" href="#test1">Misión</a></li>
                      <li class="tab col s4"><a href="#test2">Nosotros</a></li>
                      <li class="tab col s4"><a href="#test4">Visión</a></li>
                    </ul>
                  </div>
                  <div id="test1" class="col s12 justify-align margin-content-tabs">Ofrecer a nuestros clientes productos
                  naturales y orgánicos cultivados a través de un proceso natural realizado mediante formación de servicio educativo, moral y
                  espiritual de nuestros colaboradores contribuyendo a una vida saludable y plena, y lograr un bienestar en medio de un ambiente
                  moderno y ritmo de vida frenético.</div>
                  <div id="test2" class="col s12 justify-align margin-content-tabs">Productos Moisés es un departamento agroalimentario de Misión Hacia
                  Arriba. Nos dedicamos a la producción, comercialización y distribución de pollos, hortalizas, tilapia, café y miel. Uno de nuestros
                  objetivos es hacer llegar a nuestros clientes productos con la más alta calidad y máxima frescura. Contamos con la más alta
                  tecnología para la producción de alimentos y demás procesos necesarios con el fin de hacer llegar a sus casas un producto de mayor
                  calidad posible.<br><br>El Proyecto y productos Moisés, más allá de cultivar y distribuir productos, formar jóvenes fieles a Cristo Jesús
                  es nuestro motor más grande y nuestra fuerza para continuar hacia adelante, así como proveer para los hombres un ministerio entre
                  los muchachos. Tiene como meta instruir a los jóvenes en el camino correcto, orientarlos para el servicio a nuestro país formando
                  bases de rectitud e integridad en ellos, inspirarlos para crecer en su vida en todo aspecto, enseñándoles a trabajar, fomentar la
                  unidad y desarrollar sus talentos, habilidades, conocimientos y que ellos puedan desarrollarse para un futuro regresar a sus hogares
                  y ser hombres firmes, rectos que darán frutos de todo lo que aprendieron en el proyecto Moisés</div>
                  <div id="test4" class="col s12 justify-align margin-content-tabs">Ser líderes en el mercado regional de la venta de productos frescos,
                  motivando la creación de consumidores inteligentes que buscan las opciones de alimento más saludable y orgánico de alimento para
                  contribuir a su calidad de vida.</div>
                </div>
              </div>
              <div class="col s12 l6 m12 center-align">
                <img src="./img/acerca-de-productos-moises.webp" class="responsive-img" alt="productos-moises">
              </div>
            </div>
          </div>
        </div>
  </section>
  <section id="ourhistory" class="bg-gray">
      <div class="content-wrapper">
        <div class="post container">
            <div class="row">
              <div class="col s12 m12 l6 center-align">
                <img src="./img/productos-moises-sabiasque.webp" class="responsive-img" alt="sabiasque-productosmoises">
              </div>
              <div class="col s12 m12 l6">
                <h5 class="center-align no-margin sub-title">Dato</h5>
                <h3 class="center-align title no-margin">¿Sabías que?</h3>
                <div class="separate"></div>
                <div>
                  <p class="justify-align">El proyecto Moisés consta de 120 manzanas en una pequeña comunidad a las afueras de Santa Rosa de Copán.
                  Esta instalación alberga un promedio de 40 niños mayores de 13 años. Estos jóvenes realizan prácticas en los aspectos técnicos y
                  económicos de la agricultura; específicamente en caficultura, avicultura, producción avícola, producción de hortalizas y apicultura,
                  así también, procesamiento de residuos para elaboración de compost.</p>
                </div>
                <div class="center-align"><a href="/nosotros/historia"><button class="button">Ver Más...</button></a></div>
              </div>
            </div>
        </div>
      </div>
  </section>
  <section id="Ourteam" class="bg-white">
    <div class="content-wrapper">
      <div class="post container">
        <div class="row">
            <div class="heading-title text-center">
                <h5 class="center-align no-margin sub-title">Conoce nuestro equipo Moisés</h5>
                <h3 class="center-align title no-margin">Personas que aman su trabajo</h3>
                <div class="separate"></div>
                @foreach ($teams as $team)
                <div class="col s12 m6 l4">
                    <div class="team-member">
                        <div class="team-img">
                            <img src="/img/team/{{ $team->image }}" alt="	{{ $team->image_description }}" class="img-responsive-team">
                        </div>
                        <div class="team-hover">
                            <div class="desk">
                              <h4>{{ $team->greeting_title }}</h4>
                              <p>{{ $team->phrase }}</p>
                              <a href="/nosotros/equipo/{{ $team->slug }}">Leer Más...</a>
                            </div>
                        </div>
                    </div>
                    <div class="team-title">
                        <h5>{{ $team->name_team }}</h5>
                        <span>{{ $team->job_title }}</span>
                    </div>
                  </div>
                @endforeach
            </div>
          </div>
        </div>
    </div>
 </section>
@endsection

resources/views/blog.blade.php
@extends('layouts.global_main')
@section('title', 'Noticias sobre productos Moisés')
@section('urlcanonical','https://productosmoisescom/blog')
@section('description', 'Cambiando vidas a través del alcance holístico: físico, espiritual y emocional.')
@section('keywords', 'blog, noticias, productos, producción')
{{-- For FB Meta tags --}}
@section('ogtitle', 'Noticias | Productos Moisés')
@section('ogurl', 'https://productosmoises.com/blog')
@section('ogimage', 'https://productosmoises.com/img/productos-moises-noticias.jpg')
@section('ogdescription', 'Cambiando vidas a través del alcance holístico: físico, espiritual y emocional.')
{{-- End For FB Meta tags --}}
@section('content')
  <section id="parallax-phrase">
      <div class="parallax-container title-center-parallax">
        <h1 class="center-align title-parallax-view">Noticias</h1>
        <div class="parallax"><img src="/img/productos-moises-noticias.jpg" alt="blog-noticias"></div>
      </div>
  </section>
  <section id="about" class="bg-white">
    <div class="content-wrapper">
        <div class="container">
          <h5 class="center-align no-margin sub-title">Últimas noticias</h5>
          <h3 class="center-align title no-margin">Blog de noticias</h3>
          <div class="separate"></div>
          <div class="row">
            @foreach ($blogs as $key => $blog)
              @if ($key%2 != 0)
            <div class="blog-card">
                @else
            <div class="blog-card alt">
              @endif
              <div class="meta">
                <img class="photo" src="/img/blog/{{ $blog->image}}" alt="{{ $blog->slug}}">
                <ul class="details">
                  <li class="author">Fundación Moisés</li>
                  <li class="date">{{ $blog->created_at->format('M. j, Y') }}</li>
                </ul>
              </div>
              <div class="description">
                <h1>{{ $blog->title }}</h1>
                <h2>{{ $blog->subtitle }}</h2>
                <p>{!! strip_tags(str_limit(html_entity_decode($blog->content),175)) !!}</p>
                <p class="read-more">
                  <a href="blog/{{ $blog->slug}}">Read More</a>
                </p>
              </div>
            </div>
            @endforeach
          </div>
          <div class="row">
            <div class="col s12 m12 l12 center-align">
              {{ $blogs->render('manager.pagination_materialize') }}
            </div>
          </div>
        </div>
    </div>
  </section>
@endsection

resources/views/contact.blade.php
@extends('layouts.global_main')
@section('title', 'Contáctanos - Productos Moisés')
@section('urlcanonical','https://productosmoises.com/contactanos')
@section('description', 'Escribenos sin ningún compromiso')
@section('keywords', 'contacto, productos moisés')
{{-- For FB Meta tags --}}
@section('ogtitle', 'Contáctanos | Productos Moisés')
@section('ogurl', 'https://productosmoises.com/contactanos')
@section('ogimage', 'https://productosmoises.com/img/productos-moises-contactanos.jpg')
@section('ogdescription', 'Escribenos sin ningún compromiso')
{{-- End For FB Meta tags --}}
@section('content')
  <section id="parallax-phrase">
      <div class="parallax-container title-center-parallax">
        <h1 class="center-align title-parallax-view">Contáctanos</h1>
        <div class="parallax"><img src="./img/productos-moises-contactanos.jpg" alt="productos-moises-contactanos"></div>
      </div>
  </section>
  <section id="about" class="bg-white">
    <div class="content-wrapper">
        <div class="container">
          <div class="padding-top-buttom">
            <h3 class="center-align title no-margin">Contáctanos</h3>
            <h5 class="center-align no-margin sub-title">Escribenos sin ningún compromiso</h5>
          </div>
          @foreach ($errors->all() as $error)
            <li class="alert-contact-us">{{ $error }}</li>
          @endforeach
          <div class="row">
            <form action="{{ URL('/contactanos/store') }}" method="post" enctype="multipart/form-data" class="col s12">
              @csrf
              {!! RecaptchaV3::initJs() !!}
              <div class="row">
                <div class="input-field col s12 m6 l6">
                  <i class="material-icons prefix">account_circle</i>
                  <input name="name" id="name" type="text" class="validate">
                  <label for="name">Nombre</label>
                </div>
                <div class="input-field col s12 m6 l6">
                  <i class="material-icons prefix">phone</i>
                  <input name="telephone" id="telephone" type="tel" class="validate">
                  <label for="telephone">Telefono</label>
                </div>
                <div class="input-field col s12 m6 l6">
                  <i class="material-icons prefix">email</i>
                  <input name="email" id="email" type="email" class="validate">
                  <label for="email">Email</label>
                </div>
                <div class="input-field col s12 m6 l6">
                  <i class="material-icons prefix">business</i>
                  <input name="company" id="company" type="text" class="validate">
                  <label for="company">Empresa</label>
                </div>
                <div class="input-field col s12 m12 l12">
                  <i class="material-icons prefix">create</i>
                  <textarea name="comment" id="textarea1" class="materialize-textarea" data-length="120"></textarea>
                  <label for="textarea1">Comentario</label>
                </div>
              </div>
              <div class="center-align">
                <button class="button button1" type="submit" name="action">Enviar Ahora
                <i class="material-icons right">send</i>
                </button>
              </div>
              {!! RecaptchaV3::field('contacto') !!}
            </form>
          </div>
        </div>
    </div>
  </section>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
  @if ($message = Session::get('success'))
    <script type="text/javascript">
       Swal.fire({
          icon: 'success',
          title:'Success!',
          html:"<p>{{ $message }}</p>"
       })
    </script>
  @endif
@endsection

resources/views/email.blade.php
<h3>Name: </h3>
<h5>{{ $name }}</h5>

<h3>Telefono:</h3>
<h5>{{ $telephone }}</h5>

<h3>Email: </h3>
<h5>{{ $email }}</h5>

<h3>Company:</h3>
<h5> {{ $company }}</h5>

<h3>Message:</h3>
<h5> {{ $comment }}</h5>

resources/views/gallery.blade.php
@extends('layouts.global_main')
@section('title', 'Galería de imágenes - Productos Moisés')
@section('urlcanonical','https://productosmoises.com/galeria')
@section('description', 'Conoce un poco más sobre Productos Moisés')
@section('keywords', 'Galería de imágenes, Productos Moisés')
{{-- For FB Meta tags --}}
@section('ogtitle', 'Galería de imágenes y videos | Productos Moisés')
@section('ogurl', 'https://productosmoises.com/galeria')
@section('ogimage', 'https://productosmoises.com/img/galeria-imagenes-productos-moises.jpg')
@section('ogdescription', 'Conoce más sobre Productos Moisés')
{{-- End For FB Meta tags --}}
@section('content')
  <section id="parallax-phrase">
      <div class="parallax-container title-center-parallax">
        <h1 class="center-align title-parallax-view">Galería de imágenes</h1>
        <div class="parallax"><img src="./img/galeria-imagenes-productos-moises.jpg" alt="galeria-imagenes-productos-videos"></div>
      </div>
  </section>
  <section id="about" class="bg-white">
    <div class="content-wrapper">
        <div class="container">
          <h5 class="center-align no-margin sub-title">Conocenos un poco más</h5>
          <h3 class="center-align title no-margin">Galería de imágenes y videos</h3>
          <div class="row">
             <div class="col s12">
               <ul class="tabs">
                 <li class="tab col s2 m6 l2 offset-l4"><a class="active" href="#test1">Imagenes</a></li>
                 <li class="tab col s2 m6 l2"><a href="#test2">Videos</a></li>
               </ul>
             </div>
             <div id="test1" class="col s12">
               <div class="row">
                 <div class="filter">
                  @foreach ($images as $image)
                  <div class="col s12 m4 l4 padding-filtering-col filtr-item" data-category="1">
                      <img src="/img/gallery/images/{{ $image->image }}" class="responsive-img materialboxed" data-caption="{{ $image->image_text }}" alt="{{ $image->image_alt }}">
                  </div>
                   @endforeach
                 </div>
               </div>
             </div>
             <div id="test2" class="col s12">
               <div class="row">
                  @foreach ($videos as $video)
                 <div class="col s12 l4 m6 padding-filtering-col">
                    @php
                    $linkvideo = substr( $video->link_video,32 );
                    @endphp
                   <div class="video-container">
                     <iframe width="853" height="480" src="https://www.youtube.com/embed/{{ $linkvideo }}" frameborder="0" allowfullscreen></iframe>
                   </div>
                 </div>
                 @endforeach
               </div>
             </div>
          </div>
        </div>
    </div>
  </section>
@endsection

resources/views/products.blade.php
@extends('layouts.global_main')
@section('title', 'Venta de productos frescos, orgánicos y saludables')
@section('urlcanonical','https://productosmoises.com/productos')
@section('description', 'Líderes en el mercado regional de la venta de productos frescos, motivando la creación de consumidores inteligentes que buscan las opciones de alimento más saludable.')
@section('keywords', 'productos saludables, productos frescos, productos orgánicos')
{{-- For FB Meta tags --}}
@section('ogtitle', 'Producción de productos orgánicos y frescos | Productos Moisés')
@section('ogurl', 'https://productosmoises.com/productos')
@section('ogimage', 'https://productosmoises.com/img/equipo-moises.jpg')
@section('ogdescription', 'Lideres en el mercado regional en la venta de productos frescos')
{{-- End For FB Meta tags --}}
@section('content')
  <section id="parallax-phrase">
      <div class="parallax-container title-center-parallax">
        <h1 class="center-align title-parallax-view">Productos Moisés</h1>
        <div class="parallax"><img src="./img/productos-moises-pollo.jpg" alt="productos-moises-pollos"></div>
      </div>
  </section>
  <section id="products" class="bg-white">
    <div class="content-wrapper">
        <div class="container">
          <h5 class="center-align no-margin sub-title">Calidad es nuestra prioridad</h5>
          <h3 class="center-align title no-margin">Nuestros productos</h3>
          <div class="separate"></div>
          <div class="row">
            @foreach ($products as $product)
            <div class="col s12 m6 l3">
                <div class="card medium hoverable">
                  <div class="card-image">
                    <img src="/img/products/{{ $product->image_product}}" alt="{{ $product->image_alt}}">
                    <span class="card-title">{{ $product->title}}</span>
                  </div>
                  <div class="card-content">
                     {!! strip_tags(str_limit(html_entity_decode($product->content_product),143)) !!}
                     </div>
                  <div class="card-action center-align">
                    <a href="/productos/{{ $product->slug }}">Leer Más...</a>
                  </div>
                </div>
              </div>
            @endforeach
          </div>
        </div>
    </div>
  </section>
  <section id="ourhistory" class="bg-gray">
      <div class="content-wrapper">
        <div class="post container">
            <div class="row">
              <div class="col s12 m12 l6">
                <img src="./img/producto-natural.jpeg" class="responsive-img" alt="productos-naturales">
              </div>
              <div class="col s12 m12 l6">
                <h5 class="center-align no-margin sub-title">Productos de alta calidad</h5>
                <h3 class="center-align title no-margin">Producto 100% Natural</h3>
                <div class="separate"></div>
                <div>
                  <p class="justify-align">El Proyecto Moisés es una forma a largo plazo de tratar de lograr un cambio en las comunidades pobres y en todas las áreas
          				con las que cuenta. Al consumir Productos Moisés permites a los jóvenes, que de otro modo se verían obligados a abandonar la escuela, la oportunidad
          				de continuar su educación secundaria. Además, recibir capacitación espiritual a medida que se les enseña trabajo útil y habilidades para la vida.</p>
          				<p class="justify-align">Productos Moisés es una marca de propiedad absoluta de Mission UpReach, Inc., una organización sin fines de lucro 501.c.3
          				Para obtener más información sobre todos los otros trabajos que realiza Mission UpReach, visítenos en <a href="https://missionupreach.org/">missionupreach.org</a></p>
                </div>
                <div class="center-align"><a href="/contactanos"><button class="button">Contáctanos</button></a></div>
              </div>
            </div>
        </div>
      </div>
  </section>
@endsection